<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Subarea;
use Illuminate\Support\Facades\DB;

class SubareaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Subareas independientes (ya no dependen de areas)
        $subareas = [
            'Departamento de Adquisiciones',
            'Almacén',
            'Auditorio',
            'Aula Maker',
            'Centro de Autoacceso',
            'Aula Baja California',
            'Aula Bayone',
            'Aula Belfast',
            'Bodega',
            'Aula Bordeaux',
            'Aula Bradford',
            'Aula Bruxeles',
            'Aula Cambridge',
            'Centro de Medios',
            'CEYE',
            'Aula Chihuahua',
            'Centro de Información y Aprendizaje',
            'Centro de Idiomas Franco Inglés',
            'Coordinación de Cirujano Dentista',
            'Aula Clermont',
            'Clínica 1',
            'Clínica 2',
            'Clínica 3',
            'Clínica 4',
            'Clínica 5',
            'Coordinación de Comunicación',
            'Coordinación de Derecho',
            'Coordinación de Comunicación y Derecho',
            'Consejo de Administración',
            'Contabilidad y Egresos',
            'Departamento de Control Escolar',
            'Cubículo',
            'Depósito Dental',
            'Aula Derby',
            'Coordinación de Desarrollo Académico',
            'Departamento de Difusión Cultural',
            'Dirección Académica',
            'Dirección Administrativa',
            'Dirección Financiera',
            'Diseño',
            'Aula Dublín',
            'Aula Edinburgh',
            'Educación Continua',
            'Enfermería',
            'Aula Estado de México',
            'Aula Gales',
            'Aula Geneve',
            'Departamento de Gestión del Talento',
            'Coordinación de Gestión Estratégica de Imagen',
            'Aula Glasgow',
            'Aula Greenwich',
            'Aula Guerrero',
            'Aula Guyane',
            'Aula Hidalgo',
            'Coordinación de Idiomas',
            'Ingresos',
            'Aula Jalisco',
            'Laboratorio de Anatomía',
            'Laboratorio de Biomédicas',
            'Laboratorio de Ciencias',
            'Laboratorio de Prótesis 1',
            'Laboratorio de Prótesis 2',
            'Laboratorio de Prótesis 3',
            'Departamento Legal',
            'Aula Lemans',
            'Coordinación de Lenguas',
            'Aula Liverpool',
            'Aula London',
            'Aula Lyon',
            'Aula Manchester',
            'Aula Marseille',
            'Aula Martinique',
            'Aula Mérida',
            'Mezanine Cafetería',
            'Aula Michoacán',
            'Aula Mónaco',
            'Aula Montauban',
            'Aula Monterrey',
            'Aula Montpellier',
            'Aula Montreal',
            'Aula Multidisciplinaria (Espejos)',
            'Aula Nantes',
            'Coordinación de Negocios con Énfasis en Inglés',
            'Nómina',
            'Aula Nottingham',
            'Aula Nuevo León',
            'Aula Oaxaca',
            'Online',
            'Orientación',
            'Aula Ottawa',
            'Aula Oxford',
            'Aula París',
            'Prefectura Preparatoria',
            'Coordinación de Preparatoria',
            'Promotoría Deportiva',
            'Aula Quebec',
            'Aula Quintana Roo',
            'Aula Quirófano',
            'Rayos X Clínica 2',
            'Aula Rouen',
            'Departamento de RP y Mercadotecnia',
            'Sala Administrativa',
            'Sala Mac',
            'Sala de Cómputo 1',
            'Sala de Cómputo 2',
            'Sala de Cómputo 3',
            'Sala de Cómputo 4',
            'Sala de Conferencias 1',
            'Sala de Conferencias 2',
            'Sala de Discusiones',
            'Sala de Maestros CD',
            'Sala de Maestros Coordinaciones',
            'Sala de Maestros Preparatoria',
            'Aula San Luis Potosí',
            'Seguimiento a Egresados',
            'Seguridad y Bienestar',
            'Departamento de Servicios Generales',
            'Simuladores 1',
            'Simuladores 2',
            'Site Ext. Edificio Francés',
            'Site Principal',
            'Aula Sonora',
            'Aula Strasbourg',
            'Subdirección Académica',
            'Supervisión de Clínicas',
            'Aula Tabasco',
            'Aula Tahití',
            'Departamento de Tecnologías de la Información',
            'Departamento de Titulación',
            'Aula Tlaxcala',
            'Aula Tottenham',
            'Aula Toulousse',
            'Tutoría CD',
            'Tutoría Licenciaturas',
            'Salón de Usos Múltiples 1',
            'Salón de Usos Múltiples 2',
            'Aula Veracruz',
            'Vigilancia',
            'Departamento de Vinculación',
            'Aula Westham',
            'Aula 111',
            'Aula 112',
            'Aula 113',
            'Aula 121',
            'Aula 122',
            'Aula 123',
            'Aula 124',
            'Aula 125',
            'Aula 126',
            'Aula 127',
        ];

        foreach ($subareas as $subarea) {
            Subarea::create([
                'subarea' => $subarea,
            ]);
        }
    }
}
